require('core.base')
require('core.highlights')
require('core.maps')
require('plugins.init')

-- plugin configs
require('plugins.config.lspkind')
require('plugins.config.mason')
require('plugins.config.cmp')
require('plugins.config.treesitter')
require('plugins.config.lspconfig')
require('plugins.config.null-ls')
require('plugins.config.telescope')
require('plugins.config.ui')
require('plugins.config.nnn')
require('plugins.config.tree')
require('plugins.config.hop')
